services:
  survival:
    build: .
    privileged: true
    network_mode: host
    container_name: survival-project
    volumes:
        - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
        - DISPLAY=${DISPLAY}
    devices:
        - /dev/dri:/dev/dri